# Configuration for Travis-CI

language: java

sudo: false

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

env: DISPLAY=:99.0

matrix:
  include:
    - os: linux
      jdk: oraclejdk8

install: true

script: mvn -B -Dtycho.disableP2Mirrors=true -P!generateproduct integration-test

cache:
  directories:
  - $HOME/.m2

