# Configuration for Travis-CI

language: java

sudo: false

env:
  global:
    - DISPLAY=:99.0

matrix:
  include:
    - os: linux
      jdk: oraclejdk8

install: true

script: mvn -B -Dtycho.disableP2Mirrors=true install

cache:
  directories:
  - $HOME/.m2

