# Configuration for Travis-CI

language: java

sudo: false

matrix:
  include:
    - os: linux
      before_install:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3 # give xvfb some time to start
      env: DISPLAY=:99.0
      jdk: oraclejdk8

install: true

script: mvn -B -e -P!generateproduct install

cache:
  directories:
  - $HOME/.m2

